
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Feb 11 08:54:53 CET 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NAWIAS_KW_L = 6;
  public static final int DWUKROPEK = 3;
  public static final int LICZBA = 11;
  public static final int EOF = 0;
  public static final int TRIKTABLICA = 14;
  public static final int KLAMRA_OTW = 4;
  public static final int TABWARTOSCI = 12;
  public static final int ID = 10;
  public static final int PRZECINEK = 8;
  public static final int error = 1;
  public static final int TEMP = 9;
  public static final int PUSTYNULL = 13;
  public static final int CUDZYSLOW = 2;
  public static final int KLAMRA_ZAM = 5;
  public static final int NAWIAS_KW_P = 7;
}

